### ISSUE TITLE
Support named parameters

### ISSUE THREAD

**Issue by matthewmueller** [vdemedes/sushi#2]
One thing I've been thinking would be kind of cool is to support named parameters like express does. So instead of this:

``` js
app.on('start', function (args) {
  var name = args._[0];
})
```

You could do this:

``` js
app.on('start :name', function (params) {
  var name = params.name;
})
```

These could be done in addition to options.

**Comment by vadimdemedes** [comment]
I don't think it's worth it, because it is not causing any problem currently (with your first example) and it's just as easy to get those values.
